/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingworker;

import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author amyaw
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(startButton)
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusLabel.getAccessibleContext().setAccessibleName("statusLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void complicatedTask(){
        /*
        try {
            Thread.sleep(5000);            
        } catch (InterruptedException ex) {

        } 
        */
        
        
        int size = 100000;
        int array[] = new int[size];
        for(int i=0; i < size; i++){
            array[i] = (int) Math.round(Math.random());
        }
        
        for(int i=0; i < size-1; i++){
            for(int j=0; j < size-1; j++){
                if(array[j] > array[j+1]){
                    int temp = array[j];
                    array[j] = array[j+1];
                    array[j+1] = temp;
                }
            }
        }
        
        
    }
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        statusLabel.setText("Started");        
        //complicatedTask();
        //statusLabel.setText("Stopped");
                      
         
        /*
        Thread worker = new Thread(new Runnable(){
            @Override
            public void run() {
                try {                                        
                    for(int i=1; i <= 5;i++){
                        Thread.sleep(1000);                        
                        final String message = "" + i;
                        SwingUtilities.invokeLater(new Runnable(){
                            @Override
                            public void run() {
                                statusLabel.setText(message);
                            }                        
                        });
                    }
                    
                    //Thread.sleep(5000);                    
                    //complicatedTask();
                            
                    SwingUtilities.invokeLater(new Runnable(){
                        @Override
                        public void run() {
                            statusLabel.setText("Stopped");
                        }
                        
                    });
                    
                } //catch (InterruptedException ex) {
                catch (Exception ex){
                   
                }
            }            
        });
        worker.start();
        */
        
        
        StartAction worker = new StartAction();
        worker.execute();
        
    }//GEN-LAST:event_startButtonActionPerformed

    
    private class StartAction extends SwingWorker<String,String> {

        @Override
        protected String doInBackground() {
            try {
                for(int i=0; i < 5; i++){
                    Thread.sleep(1000);
                    publish("" + (i+1));
                }
                Thread.sleep(1000);                
            } catch (InterruptedException ex) {
              
            }
            return "stopped";
        }
        
        protected void process(List<String> messages){
            statusLabel.setText(messages.get(0));
        }
                        
        @Override
        protected void done() {
            try {                
                statusLabel.setText(get());
            } catch (InterruptedException ex) {
                
            } catch (ExecutionException ex) {
               
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
