const fs = require('fs');

// HTML content
const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Page</title>
</head>
<body>
  <h1>Hello World!</h1>
  <p>This is a new HTML page generated by Create1.js.</p>
</body>
</html>
`;

const filePath = 'new_page.html';

fs.writeFile(filePath, htmlContent, (err) => {
    if (err) {
        console.error('Error writing file:', err);
        return;
    }
    console.log('HTML file created successfully!');
});
