/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author farooq
 */
public class Temperature extends javax.swing.JFrame {
    
    private int option;

    /**
     * Creates new form Temperature
     */
    public Temperature() {
        initComponents();        
        option = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupOptions = new javax.swing.ButtonGroup();
        txtTemp = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        lblTo = new javax.swing.JLabel();
        radioCtoF = new javax.swing.JRadioButton();
        radioFtoC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblFrom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFrom.setText("Celcius");

        btnConvert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lblTo.setText("Fahrenheit");

        groupOptions.add(radioCtoF);
        radioCtoF.setSelected(true);
        radioCtoF.setText("Celcius to Fahrenheit");
        radioCtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCtoFActionPerformed(evt);
            }
        });

        groupOptions.add(radioFtoC);
        radioFtoC.setText("Fahrenheit to Celcius");
        radioFtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFtoCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioFtoC)
                    .addComponent(radioCtoF)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTemp)
                            .addComponent(btnConvert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTo)
                            .addComponent(lblFrom))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(radioCtoF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioFtoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblFrom))
                    .addComponent(txtTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert)
                    .addComponent(lblTo))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        try{
            float from = Float.parseFloat(txtTemp.getText());
            float to = convert(from);
            
            lblTo.setText(to + (option == 1 ? " Fahrenheit" : " Celcius"));
            
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(getContentPane(), "Invalid number");
            txtTemp.setText("");
        }       
    }//GEN-LAST:event_btnConvertActionPerformed

    private void radioCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCtoFActionPerformed
        lblFrom.setText("Celcius");
        lblTo.setText("Fahrenheit");
        txtTemp.setText("");
        option = 1;
    }//GEN-LAST:event_radioCtoFActionPerformed

    private void radioFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFtoCActionPerformed
        lblFrom.setText("Fahrenheit");
        lblTo.setText("Celcius");
        txtTemp.setText("");
        option = 2;
    }//GEN-LAST:event_radioFtoCActionPerformed

    private float convert(float v){
        float r = 0;
        if (option == 1){
            r = v * 9 / 5 + 32;
        }
        else {
            r = (v - 32) * 5 / 9; 
        }
        r = (float) Math.round(r * 10) / 10;
        
        return r;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.ButtonGroup groupOptions;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton radioCtoF;
    private javax.swing.JRadioButton radioFtoC;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
