/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphicsEditor.java
 *
 * Created on Oct 18, 2011, 11:03:27 PM
 */

package graphics.ui;

import graphics.core.Canvas;
import graphics.core.Shape;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Iterator;

/**
 *
 * @author farooq
 */
public class GraphicsEditor extends javax.swing.JFrame {

    Canvas canvas;
    ShapesListModel shapesModel;

    /** Creates new form GraphicsEditor */
    public GraphicsEditor() {
        initComponents();
        canvas = new Canvas(pnlCanvas.getGraphics());
        setMaxCoordinates();
        shapesModel = new ShapesListModel();
        lstShapes.setModel(shapesModel);        
        lstShapes.addMouseListener(new ShapesListMouseListener());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pnlCanvas = new javax.swing.JPanel();
        lblCoordinates = new javax.swing.JLabel();
        btnRectangle = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnCircle = new javax.swing.JButton();
        lblMaxCoordinates = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstShapes = new javax.swing.JList();
        lblList = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlCanvas.setBackground(java.awt.Color.white);
        pnlCanvas.setBorder(javax.swing.BorderFactory.createTitledBorder("Canvas"));
        pnlCanvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlCanvasMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout pnlCanvasLayout = new javax.swing.GroupLayout(pnlCanvas);
        pnlCanvas.setLayout(pnlCanvasLayout);
        pnlCanvasLayout.setHorizontalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCanvasLayout.setVerticalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        btnRectangle.setText("Create Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnSquare.setText("Create Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnCircle.setText("Create Circle");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstShapes);

        lblList.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblList.setText("Shapes List");

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonLoad.setText("Load");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoordinates, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCanvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaxCoordinates)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRectangle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSquare)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCircle)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLoad)))
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblList)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblList)
                    .addComponent(btnRectangle)
                    .addComponent(btnSquare)
                    .addComponent(btnCircle)
                    .addComponent(buttonSave)
                    .addComponent(buttonLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoordinates)
                    .addComponent(lblMaxCoordinates))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCanvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCanvasMouseMoved
        Point p = pnlCanvas.getMousePosition();
        String coordinates = "(" + p.x + "," + p.y + ")";
        lblCoordinates.setText(coordinates);
    }//GEN-LAST:event_pnlCanvasMouseMoved

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        RectangleForm form = new RectangleForm(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        SquareForm form = new SquareForm(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        CircleForm form = new CircleForm(this, true);
        form.setVisible(true);        
    }//GEN-LAST:event_btnCircleActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        canvas.save();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        canvas.load();
        Iterator<Shape> shapes = canvas.getIterator();

        while(shapes.hasNext()){
            addShape(shapes.next());
        }

        canvas.repaint();
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void setMaxCoordinates(){
        String min = "(0,0)";
        String max = "(" + pnlCanvas.getWidth() + "," + pnlCanvas.getHeight() + ")";

        lblMaxCoordinates.setText( min + " : " + max);

    }

    public void paint(Graphics g){
        super.paint(g);
        canvas.repaint();
    }

    public void addShape(Shape s){
        
        shapesModel.addElement(s);

    }

    public void repaintCanvas(){
        pnlCanvas.removeAll();
        pnlCanvas.repaint();
        canvas.repaint();
    }

    private class ShapesListMouseListener implements MouseListener{

        public void mouseClicked(MouseEvent e) {
                MoveForm form = new MoveForm(GraphicsEditor.this, true,(Shape)shapesModel.getElementAt(lstShapes.getSelectedIndex()));
                form.setVisible(true);
        }

        public void mousePressed(MouseEvent e) {

        }

        public void mouseReleased(MouseEvent e) {

        }

        public void mouseEntered(MouseEvent e) {

        }

        public void mouseExited(MouseEvent e) {
            
        }

    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonSave;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCoordinates;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblMaxCoordinates;
    private javax.swing.JList lstShapes;
    private javax.swing.JPanel pnlCanvas;
    // End of variables declaration//GEN-END:variables

}
